name: rexios
description: A simple bootstrap utility for all of the CLI tools I daily drive
version: 1.0.0
homepage: https://github.com/Rexios80/rexios

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  rexios_lints: ^5.0.0

executables:
  fluttercors: flutter_cors
  git_dependency_prs: git_dependency_prs
  opd: one_password_dart
  oie: open_in_editor
  puby: puby
  rex: rex
